name: Run tests with twister V2

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'A scope to scan for tests'
        default: 'tests/kernel/common'
        required: false
        type: string
  workflow_call:
    inputs:
      scope:
        description: 'A scope to scan for tests'
        default: 'tests/kernel/common'
        required: false
        type: string

jobs:
  twisterV2:
    runs-on: ubuntu-latest
    name: Run tests with twisterv2
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.24.6
      options: '--entrypoint /bin/bash'
    strategy:
      fail-fast: false
      matrix:
        subset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    env:
      MATRIX_SIZE: 10
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.15.2
      BASE_REF: ${{ github.base_ref }}
      ZEPHYR_BASE: ""
    steps:
      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Checkout Zephyr
        uses: actions/checkout@v3
        with:
          repository: 'zephyrproject-rtos/zephyr'
          path: 'zephyr'

      - name: Checkout Twister
        uses: actions/checkout@v3
        with:
          path: twisterV2

      - name: Install twister
        working-directory: twisterV2
        run: |
          pip install -r requirements.txt -r requirements-tests.txt -r requirements-dev.txt
          pip install pytest-split
          pip install .

      - name: Configure environment
        working-directory: zephyr
        run: |
          echo "ZEPHYR_BASE=$PWD" >> $GITHUB_ENV
          west init -l . || true
          west update --narrow

      - name: Run twister
        working-directory: zephyr
        run: |
          echo "Running scope: ${{ inputs.scope }}"
          pytest ${{ inputs.scope }} --zephyr-base=$ZEPHYR_BASE --platform=qemu_cortex_m3 --platform=qemu_x86 -v --results-json=twister-out/results_${{matrix.subset}}.json -n auto --splits=${MATRIX_SIZE} --group=${{ matrix.subset }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: report_twisterV2
          path: zephyr/twister-out/results_${{ matrix.subset }}.json
