name: Dispatch and compare tests run with twister V1 and  V2

on:
  workflow_dispatch:
    inputs:
      scope:
        args:
          description: 'Test scope'
          required: true
          default: "tests/kernel/common"
  pull_request:
    branches:
      - main

jobs:
  call-v2-passing-data:
    uses: ./.github/workflows/comparison_v2.yaml
    with:
      scope: ${{ inputs.scope }}

  download-artifacts-v2:
    - uses: actions/download-artifact@v3
      needs: [call-v2-passing-data]
      with:
        path: results/resv2

  name: Display structure of downloaded files
  working-directory: results
  run: |
    ls -R
