on:
  workflow_dispatch:
    inputs:
      args:
        description: 'Args passed to twister call'
        required: true
  pull_request:
      branches:
      - main
jobs:
  twister-build-prep:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.24.6
      options: '--entrypoint /bin/bash'
    env:
     MATRIX_SIZE: 10
     ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.15.2
     BASE_REF: ${{ github.base_ref }}
    steps:
      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
    # - name: Checkout Zephyr
    #   uses: actions/checkout@v3
    #   with:
    #     repository: 'zephyrproject-rtos/zephyr'
    #     path: 'zephyr'
    - name: Checkout Twister
      uses: actions/checkout@v3
    - name: Install twister
      run: |
        tree
        pip install -r requirements.txt -r requirements-tests.txt -r requirements-dev.txt
    - name: Run twister
      run: |
        pytest zephyr/tests/kernel/common -v --zephyr-base=./zephyr