name: Run tests with twister V1

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'A scope to scan for tests'
        default: 'tests/kernel/common'
        required: false
        type: string
      args_raw:
        description: 'Raw string of args added to twister call'
        required: false
        type: string
  workflow_call:
    inputs:
      scope:
        description: 'A scope to scan for tests'
        default: 'tests/kernel/common'
        required: true
        type: string
      args_raw:
        description: 'Raw string of args added to twister call'
        required: false
        type: string
jobs:
  twisterV1:
    runs-on: ubuntu-latest
    name: Run tests with twisterV1
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.24.6
      options: '--entrypoint /bin/bash'
    strategy:
      fail-fast: false
      matrix:
        subset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    env:
      MATRIX_SIZE: 10
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.15.2
      BASE_REF: ${{ github.base_ref }}
      ZEPHYR_BASE: ""
    steps:
      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Checkout Zephyr
        uses: actions/checkout@v3
        with:
          repository: 'zephyrproject-rtos/zephyr'
          path: 'zephyr'

      - name: Configure environment
        working-directory: zephyr
        run: |
          echo "ZEPHYR_BASE=$PWD" >> $GITHUB_ENV
          west init -l . || true
          west update --narrow
          # FIXME: quick fix to remove not working pytests tests
          rm -rf samples/modules/tflite-micro
          # FIXME: quick fix to remove wrong yaml files
          rm samples/drivers/i2s/litex/sample.yaml
          rm samples/net/sockets/tcp/sample.yaml
          # FIXME: v1 "pytest" tests, need rework
          rm -rf samples/subsys/testsuite/pytest
          # FIXME: remove slow tests
          rm -rf tests/kernel/fpu_sharing/generic/testcase.yaml
          rm -rf tests/kernel/timer/cycle64/testcase.yaml
          rm -rf kernel/timer/starve/testcase.yaml

      - name: Run twister
        working-directory: zephyr
        shell: bash
        run: |
          export ZEPHYR_BASE
          export SCOPE=""
          for folder in ${{ inputs.scope }}
          do
              SCOPE+=" -T $folder"
          done
          echo "Running scope: $SCOPE"
          echo "Extra args: ${{ inputs.args_raw }}"
          ./scripts/twister $SCOPE ${{ inputs.args_raw }} -v --subset ${{ matrix.subset }}/${MATRIX_SIZE}

      - name: Copy results
        if: ${{ always() }}
        working-directory: zephyr
        run: |
          # Add unique name to the results for the purpouse of uploading
          echo "copy results"
          cp twister-out/twister.json twister-out/results_${{ matrix.subset }}.json

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: report_twisterV1
          path: zephyr/twister-out/results_${{ matrix.subset }}.json
