name: Dispatch and compare tests run with twister V1 and  V2

on:
  workflow_dispatch:
    inputs:
      scope:
        args:
          description: 'Test scope'
          required: true
          default: "tests/kernel/common"

jobs:
  call-v2-passing-data:
    uses: ./.github/workflows/comparison_v2.yaml
    with:
      scope: ${{ inputs.scope }}

  handle-v2-reports:
    runs-on: ubuntu-latest
    name: Prepare v2 report
    if: ${{ always() }}
    needs: [call-v2-passing-data]
    steps:
      - name: Download artifacts v2
        uses: actions/download-artifact@v3
        with:
          path: results/resv2
          name: report_twisterV2

      - name: Checkout Twister
        uses: actions/checkout@v3
        with:
          path: twisterV2

      - name: Merge v2 reports
        run: |
          ls -R
          ./twisterV2/src/twister2/scripts/merge_twister_json.py --v2-reports=results/resv2 

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: report_merged_twisterV2
          path: results/resv2/results_v2_merged.json
