name: Dispatch and compare tests run with twister V1 and  V2

on:
  workflow_dispatch:
    scope:
      args:
        description: 'Test scope'
        required: true
        default: "tests/kernel/common"
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/comparison_v2.yaml
    with:
      scope: ${{ inputs.scope }}
